### ISSUE TITLE
Remove "less than", "about" prefixes?

### ISSUE THREAD

**Issue by jaimeiniesta** [marcreichel/alpine-timeago#6]
Hi!

I see there's an option to remove the "ago" suffix, but I don't see how to remove the prefixes for "less than", "about", etc.

In some cases I find this handy to produce shorter strings, so for example:

"less than 20 seconds ago" -> "20 seconds ago"
"less than a minute ago" -> "a minute ago"
"about 20 hours ago" -> "20 hours ago"

**Comment by marcreichel** [comment]
@jaimeiniesta Thanks for requesting this feature.

I've implemented it in version 1.4.0 👍🏼 Feel free to update 👍🏼 The docs for the directive can be found [here](https://github.com/marcreichel/alpine-timeago#strict) and the docs for the magic function can be found [here](https://github.com/marcreichel/alpine-timeago#strict-1).

**Comment by jaimeiniesta** [comment]
Wow, that was quick, thanks!
